---
title: "HAWC_Data_Preparation"
author: "Chelsea Christie"
date: "01/13/2023"
output: word_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Start with loading packages

```{r load_packages, echo=FALSE}

# Load/Install required packages ---------------------

pacman::p_load(effectsize, ggeffects, ggpubr, ggstatsplot, janitor, interactions, jtools, knitr, parameters, rio, remotes, report, rstatix, tidyverse,  see, sjPlot, sjmisc) 

```

# Bring in data, rename variables, drop non-CMA DAs, and check for duplicates

```{r}

########################## Can-ALE data ##########################################

Can_ALE_2016_dataset <- rio::import("Data & metadata/CanALE_2016.csv") %>% 
 rename(
   "DA_ID" ="dauid",
    "intersections_2016" ="int_d",
    "dwelling_density_2016" ="dwl_d",
    "z_intersections_2016" ="z_int_d",
    "z_dwelling_density_2016" ="z_dwl_d",
    "z_ALE_score_2016" ="ale_index",
    "ALE_class_2016" ="ale_class",
    "points_of_interest_2016" ="poi",
    "z_points_of_interest_2016" ="z_poi",
    "transit_stops_2016" ="transit",
    "z_transit_stops_2016" ="z_transit",
    "ALE_transit_score_2016" ="ale_tranist",
    "ALE_transit_class_2016" ="ale_transit_class")

# Are there any DAs that are duplicated?
Can_ALE_2016_dataset$DA_ID[duplicated(Can_ALE_2016_dataset$DA_ID)] 
length(unique(Can_ALE_2016_dataset$DA_ID))

# is there any missing data?
sapply(Can_ALE_2016_dataset, function(x) sum(is.na(x))) 

########################## Census data ##########################################

######### 2016 census data
 
 # read in part 1 data (from Paul Pival)

census_2016_dataset <- rio::import("Data & metadata/2016_raw-census-data_2021_05_28.xls") %>% 
 select(c("DAUID", "CMATYPE", "CMANAME", "CMAUID", "PRNAME", "PRUID", "ONE", "TWO", "THREE", "FOUR", "FIVE", "SIX", "SEVEN", "EIGHT", "NINE", "TEN", "ELEVEN", "TWELVE")) %>%
rename(
   "DA_ID" = "DAUID",
    "CMA_yes_or_no_2016" = "CMATYPE",
    "CMA_name_2016" = "CMANAME",
    "CMA_ID_number_2016" = "CMAUID",
    "province_name_2016" = "PRNAME",
    "province_ID_number_2016" = "PRUID",
    "private_households_by_tenure_2016" = "ONE",
    "overall_households_with_income_2016" = "TWO",
    "owners_percent_with_mortgage_2016" = "THREE",
    "owners_percent_overpaying_for_shelter_2016" = "FOUR",
    "owners_median_shelter_costs_2016" = "FIVE",
    "owners_mean_shelter_costs_2016" = "SIX",
    "median_dwelling_value_2016" = "SEVEN",
    "mean_dwelling_value_2016" = "EIGHT",
    "subsidized_housing_percent_2016" = "NINE",
    "tenants_percent_overpaying_for_shelter_2016" = "TEN",
    "tenants_median_shelter_costs_2016" = "ELEVEN",
    "tenants_mean_shelter_costs_2016" = "TWELVE")

# Are there any DAs that are duplicated?
census_2016_dataset$DA_ID[duplicated(census_2016_dataset$DA_ID)] 
length(unique(census_2016_dataset$DA_ID)) # 0 duplicates

# is there any missing data?
sapply(census_2016_dataset, function(x) sum(is.na(x))) # returns the number of missing values there are for each variable


## Bring in part 2 of 2016 census data (downloaded by Chelsea from the Canadian Census Analyzer)
 
updated_census_2016_dataset <- rio::import("Data & metadata/raw census data downloaded by Chelsea/UPDATED_2016_CENSUS_DATA.csv") %>%  rename(
      "DA_ID" = "COL0",
      "census_ID_2016" = "COL1",
      "total_dwellings_by_age_2016" = "COL2",
      "dwellings_before_1960_2016" = "COL3",
      "dwellings_61_to_80_2016" = "COL4",
      "dwellings_81_to_90_2016" = "COL5",
      "dwellings_91_to_00_2016" = "COL6",
      "dwellings_01_to_05_2016" = "COL7",
      "dwellings_06_to_10_2016" = "COL8",
      "dwellings_11_to_16_2016" = "COL9",
      "avg_rooms_2016" = "COL10",
      "total_dwellings_by_condo_status" = "COL11",
      "condos_2016" = "COL12",
      "non_condos_2016" = "COL13",
      "total_dwellings_by_condition_2016" = "COL14",
      "dwellings_regular_maintenance_2016" = "COL15",
      "dwellings_needing_repairs_2016" = "COL16",
      "total_population_by_minority_2016" = "COL20",
      "minorities_2016" = "COL21",
      "non_minorities_2016" = "COL22",
      "total_population_by_immigrant_2016" = "COL23",
      "non_immigrants_2016" = "COL24",
      "immigrants_2016" = "COL25",
      "non_permanent_residents_2016" = "COL26",
      "total_dwellings_by_type_2016" = "COL27",
      "detached_houses_2016" = "COL28",
      "tall_apartments_2016" = "COL29",
      "other_attached_dwellings_2016" = "COL30",
      "movable_dwellings_2016" = "COL31",
      "total_dwellings_by_tenure_2016" = "COL32",
      "owned_dwellings_2016" = "COL33",
      "rented_dwellings_2016" = "COL34",
      "band_dwellings_2016" = "COL35",
      "total_mobility_one_year_2016" = "COL36",
      "non_movers_one_year_2016" = "COL37",
      "movers_one_year_2016" = "COL38",
      "total_mobility_five_year_2016" = "COL39",
      "non_movers_five_year_2016" = "COL40",
      "movers_five_year_2016" = "COL41")

# Are there any DAs that are duplicated?
length(unique(updated_census_2016_dataset$DA_ID)) # none

# is there any missing data?
sapply(updated_census_2016_dataset, function(x) sum(is.na(x))) # returns the number of missing values there are for each variable

## Bring in part 3 of 2016 census data (downloaded by Chelsea from the Canadian Census Analyzer)
 
household_income_census_2016_dataset <- rio::import("Data & metadata/raw census data downloaded by Chelsea/Household_income_2016_data.csv") %>%  rename(
      "DA_ID" = "COL0",
      "median_income_2016" = "COL3")

# Are there any DAs that are duplicated?
length(unique(household_income_census_2016_dataset$DA_ID)) # none

# is there any missing data?
 sapply(household_income_census_2016_dataset, function(x) sum(is.na(x))) # returns the number of missing values there are for each variable

```

# Merge datasets

```{r}

################# combine 2016 census data with 2016 Can-ALE data ##############################


# check that the merging variable (DA_ID) are non-character/string variable types in all 3 datasets

str(Can_ALE_2016_dataset$DA_ID)
str(census_2016_dataset$DA_ID) # character type
str(updated_census_2016_dataset$DA_ID)
str(household_income_census_2016_dataset$DA_ID)

# first need to convert DA_ID variable in the old census dataset from character to numeric type

census_2016_dataset$DA_ID <- as.numeric(census_2016_dataset$DA_ID)

str(census_2016_dataset$DA_ID) # good to see that DA_ID is numeric now too

# Can_ALE 2016 has 56 589 observations and 13 variables
# Census 2016 data has 36 169 observations and 18 variables
# Updated 2016 census data has 56883 observations and 42 variables
# merged data should have 36 169 observations and 74 variables (13 + 18 + 42 + 4 - 3 (for the duplicated DA_ID variable)

# merging the 2016 datasets (using left_join so that we only get all the rows included in the census_2016_dataset)

partway_dataset_2016 <- left_join(census_2016_dataset, Can_ALE_2016_dataset, by="DA_ID")
str(partway_dataset_2016) 

partway_dataset_2_2016 <- left_join(partway_dataset_2016, updated_census_2016_dataset, by="DA_ID")
str(partway_dataset_2016) 

dataset_2016 <- left_join(partway_dataset_2_2016, household_income_census_2016_dataset, by = "DA_ID")
str(dataset_2016)

```

# Save the merged dataset

```{r}

saveRDS(dataset_2016, file = "dataset_2016.rds")

```


